Code for Question 1

In [1]:
# code for question 1- (1)
>>> type("Hello, World!")

str

In [2]:
# code for question 1- (2)
>>> type(17)

int

In [3]:
# code for question 1- (3)
>>> type(3.2)

float

In [4]:
# code for question 1- (4)
>>> type("3.2")

str

In [5]:
# code for question 1- (5)
>>> type("17")

str

In [6]:
>>> type('This is a string.')
>>> type("And so is this.")
>>> type("""and this.""")
>>> type('''and even this...''')

str

In [7]:
>>> print('''"Oh no", she exclaimed, "Ben's bike is broken!"''')

"Oh no", she exclaimed, "Ben's bike is broken!"


In [8]:
>>> message = """This message will
... span several
... lines."""
>>> print(message)

This message will
span several
lines.


In [9]:
>>> 'This is a string.'

'This is a string.'

In [10]:
>>> """And so is this."""

'And so is this.'

In [63]:
>>> 42000

42000

In [64]:
>>> 42,000

(42, 0)

In [70]:
>>> message = "What's up, Doc?"
>>> n = 17
>>> pi = 3.14159
print(message)

What's up, Doc?


In [71]:
>>> message = "What's up, Doc?"
>>> n = 17
>>> pi = 3.14159
print(17)

17


In [72]:
>>> message = "What's up, Doc?"
>>> n = 17
>>> pi = 3.14159
print(pi)

3.14159


In [73]:
>>> day = "Thursday"
>>> day

'Thursday'

In [74]:
>>> day = "Friday"
>>> day

'Friday'

In [75]:
>>> day = 21
>>> day

21

In [76]:
>>> 1 + 1

2

In [77]:
>>> len("hello")

5

In [78]:
>>> 17

17

In [79]:
>>> y = 3.14
>>> x = len("hello")
>>> x

5

In [80]:
>>> y = 3.14
>>> x = len("hello")
>>> y

3.14

In [81]:
>>> 2 ** 3

8

In [ ]:
>>> 3 ** 2

In [82]:
>>> minutes = 645
>>> hours = minutes / 60
>>> hours

10.75

In [83]:
>>> 7 / 4

1.75

In [84]:
>>> 7 // 4

1

In [85]:
>>> minutes = 645
>>> hours = minutes // 60
>>> hours

10

In [87]:
>>> int(3.14)
3
>>> int(3.9999) # This doesn't round to the closest int!
3
>>> int(3.0)
3
>>> int(-3.999) # Note that the result is closer to zero
-3
>>> int(minutes / 60)
10
>>> int("2345") # Parse a string to produce an int
2345
>>> int(17) # It even works if arg is already an int
17

17

In [88]:
>>> float(17)

17.0

In [89]:
>>> float("123.45")

123.45

In [90]:
>>> str(17)

'17'

In [91]:
>>> str(123.45)

'123.45'

In [92]:
>>> 2 ** 3 ** 2

512

In [93]:
>>> (2 ** 3) ** 2

64

In [11]:
fruit = "banana"
baked_good = " nut bread"
print(fruit + baked_good)

banana nut bread


In [12]:
>>> q = 7 // 3 # This is integer division operator
>>> print(q)

2


In [13]:
>>> r = 7 % 3
>>> print(r)

1


In [14]:
# This begins the questions for chapter 3
>>> type(True)
<class 'bool'>
>>> type(true)
Traceback (most recent call last):
File "<interactive input>", line 1, in <module>

SyntaxError: invalid syntax (<ipython-input-14-46a8ef68285e>, line 3)

In [15]:
>>> 5 == (3 + 2) # Is five equal 5 to the result of 3 + 2?

True

In [16]:
>>> 5 == 6

False

In [17]:
>>> j = "hel"
>>> j + "lo" == "hello"

True

In [18]:
>>> age = 19
>>> old_enough_to_get_driving_licence = age >= 18
>>> print(old_enough_to_get_driving_licence)

True


In [19]:
>>> type(old_enough_to_get_driving_licence)
<class 'bool'>

SyntaxError: invalid syntax (<ipython-input-19-d495431a05e5>, line 2)

In [20]:
>>> w = x + 1
Traceback (most recent call last):
File "<interactive input>", line 1, in

SyntaxError: invalid syntax (<ipython-input-20-141ad1512786>, line 2)

In [21]:
# This begins the questions for chapter 4
>>> abs(5)

5

In [22]:
>>> abs(-5)

5

In [23]:
>>> pow(2, 3)

8

In [24]:
>>> pow(7, 4)

2401

In [25]:
>>> max(7, 11)

11

In [26]:
>>> max(4, 1, 17, 2, 12)

17

In [27]:
>>> max(3 * 11, 5**3, 512 - 9, 1024**0)

503

In [28]:
>>> find_first_2_letter_word(["This", "is", "a", "dead", "parrot"])

NameError: name 'find_first_2_letter_word' is not defined

In [29]:
>>> find_first_2_letter_word(["I", "like", "cheese"])

NameError: name 'find_first_2_letter_word' is not defined

In [30]:
>>> distance(1, 2, 4, 6)

NameError: name 'distance' is not defined

In [31]:
>>> things = [2, 5, 9]
>>> more_things = double_stuff(things)
>>> things

NameError: name 'double_stuff' is not defined

In [32]:
>>> things = [2, 5, 9]
>>> more_things = double_stuff(things)
>>> more_things

NameError: name 'double_stuff' is not defined

In [ ]:
>>> things = [2, 5, 9]
>>> things = double_stuff(things)
>>> things

In [ ]:
>>> things = [2, 5, 9]
>>> more_things = double_stuff(things)
>>> things

In [ ]:
>>> things = [2, 5, 9]
>>> more_things = double_stuff(things)
>>> more_things

In [33]:
# This begins the questions for chapter 5
>>> our_string = "Hello, World!"
>>> all_caps = our_string.upper()
>>> all_caps

'HELLO, WORLD!'

In [34]:
>>> fruit = "banana"
>>> letter = fruit[1]
>>> print(letter)

a


In [35]:
>>> letter = fruit[0]
>>> print(letter)

b


In [36]:
>>> fruit = "banana"
>>> list(enumerate(fruit))

[(0, 'b'), (1, 'a'), (2, 'n'), (3, 'a'), (4, 'n'), (5, 'a')]

In [37]:
>>> prime_numbers = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31]
>>> prime_numbers[4]

11

In [38]:
>>> friends = ["Joe", "Zoe", "Brad", "Angelina", "Zuki", "Thandi", "Paris"]
>>> friends[3]

'Angelina'

In [39]:
>>> word = "banana"
>>> len(word)

6

In [40]:
>>> phrase = "Pirates of the Caribbean"
>>> print(phrase[0:7])

Pirates


In [41]:
>>> print(phrase[11:14])

the


In [42]:
>>> print(phrase[13:24])

e Caribbean


In [43]:
>>> friends = ["Joe", "Zoe", "Brad", "Angelina", "Zuki", "Thandi", "Paris"]
>>> print(friends[2:4])

['Brad', 'Angelina']


In [44]:
>>> word = "banana"
>>> word[:3]

'ban'

In [45]:
>>> word[3:]

'ana'

In [46]:
>>> word[3:999]

'ana'

In [47]:
>>> "p" in "apple"

True

In [48]:
>>> "i" in "apple"

False

In [49]:
>>> "ap" in "apple"

True

In [50]:
>>> "pa" in "apple"

False

In [51]:
>>> "a" in "a"

True

In [52]:
>>> "apple" in "apple"

True

In [53]:
>>> "" in "a"

True

In [54]:
>>> "" in "apple"

True

In [55]:
>>> "banana".find("nan")

2

In [56]:
>>> "banana".find("na", 3)

4

In [57]:
>>> phrase = "Well I never did said Alice"
>>> words = phrase.split()
>>> words

['Well', 'I', 'never', 'did', 'said', 'Alice']

In [58]:
>>> "hello {3}".format("Dave")
Traceback (most recent call last):
File "<interactive input>", line 1, in <module>

SyntaxError: invalid syntax (<ipython-input-58-ce5c534381bf>, line 2)

In [66]:
>>> year_born = ("Paris Hilton", 1981)

In [69]:
>>> julia = ("Julia", "Roberts", 1967, "Duplicity", 2009, "Actress",
"Atlanta, Georgia")
>>> julia[2]

1967

In [70]:
>>> julia = ("Julia", "Roberts", 1967, "Duplicity", 2009, "Actress",
"Atlanta, Georgia")
>>> julia[2]

1967

In [71]:
>>> julia = ("Julia", "Roberts", 1967, "Duplicity", 2009, "Actress",
"Atlanta, Georgia")
>>> julia = julia[:3] + ("Eat Pray Love", 2010) + julia[5:]
>>> julia

('Julia',
 'Roberts',
 1967,
 'Eat Pray Love',
 2010,
 'Actress',
 'Atlanta, Georgia')

In [72]:
>>> tup = (5,)
>>> type(tup)

tuple

In [73]:
>>> x = (5)
>>> type(x)

int

In [77]:
>>> bob = ("Bob", 19, "CS")

In [76]:
>>> bob = ("Bob", 19, "CS")
>>> (name, age, studies) = bob # tuple unpacking
>>> name

'Bob'

In [78]:
>>> bob = ("Bob", 19, "CS")
>>> (name, age, studies) = bob # tuple unpacking
>>> age

19

In [79]:
>>> bob = ("Bob", 19, "CS")
>>> (name, age, studies) = bob # tuple unpacking
>>> studies

'CS'

In [80]:
>>> (one, two, three, four) = (1, 2, 3)

ValueError: not enough values to unpack (expected 4, got 3)

In [92]:
>>> vocabulary = ["apple", "cheese", "dog"]
>>> numbers = [17, 123]
>>> an_empty_list = []
>>> print(vocabulary, numbers, an_empty_list)

['apple', 'cheese', 'dog'] [17, 123] []


In [91]:
>>> vocabulary = ["apple", "cheese", "dog"]
>>> numbers = [17, 123]
>>> an_empty_list = []
>>> print(vocabulary, numbers, an_empty_list)
>>> numbers[0]

['apple', 'cheese', 'dog'] [17, 123] []


17

In [87]:
>>> vocabulary = ["apple", "cheese", "dog"]
>>> numbers = [17, 123]
>>> an_empty_list = []
>>> numbers[9-8]

123

In [94]:
>>> vocabulary = ["apple", "cheese", "dog"]
>>> numbers = [17, 123]
>>> an_empty_list = []
>>> numbers[1.0]

TypeError: list indices must be integers or slices, not float

In [93]:
>>> vocabulary = ["apple", "cheese", "dog"]
>>> numbers = [17, 123]
>>> an_empty_list = []
>>> numbers[2]

IndexError: list index out of range

In [95]:
>>> len(["car makers", 1, ["Ford", "Toyota", "BMW"], [1, 2, 3]])

4

In [96]:
>>> horsemen = ["war", "famine", "pestilence", "death"]
>>> "pestilence" in horsemen

True

In [97]:
>>> "debauchery" in horsemen

False

In [98]:
>>> "debauchery" not in horsemen

True

In [99]:
>>> first_list = [1, 2, 3]
>>> second_list = [4, 5, 6]
>>> both_lists = first_list + second_list
>>> both_lists

[1, 2, 3, 4, 5, 6]

In [100]:
>>> [0] * 4

[0, 0, 0, 0]

In [101]:
>>> [1, 2, 3] * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [102]:
>>> a_list = ["a", "b", "c", "d", "e", "f"]
>>> a_list[1:3]

['b', 'c']

In [103]:
>>> a_list[:4]

['a', 'b', 'c', 'd']

In [104]:
>>> a_list[3:]

['d', 'e', 'f']

In [105]:
>>> a_list[:]

['a', 'b', 'c', 'd', 'e', 'f']

In [106]:
>>> fruit = ["banana", "apple", "quince"]
>>> fruit[0] = "pear"
>>> fruit[2] = "orange"
>>> fruit

['pear', 'apple', 'orange']

In [107]:
>>> my_list = ["T", "E", "S", "T"]
>>> my_list[2] = "X"
>>> my_list

['T', 'E', 'X', 'T']

In [108]:
>>> a_list = ["a", "b", "c", "d", "e", "f"]
>>> a_list[1:3] = ["x", "y"]
>>> a_list

['a', 'x', 'y', 'd', 'e', 'f']

In [109]:
>>> a_list = ["a", "b", "c", "d", "e", "f"]
>>> a_list[1:3] = []
>>> a_list

['a', 'd', 'e', 'f']

In [110]:
>>> a_list = ["a", "d", "f"]
>>> a_list[1:1] = ["b", "c"]
>>> a_list

['a', 'b', 'c', 'd', 'f']

In [111]:
>>> a_list[4:4] = ["e"]
>>> a_list

['a', 'b', 'c', 'd', 'e', 'f']

In [112]:
>>> a = ["one", "two", "three"]
>>> del a[1]
>>> a

['one', 'three']

In [113]:
>>> a_list = ["a", "b", "c", "d", "e", "f"]
>>> del a_list[1:5]
>>> a_list

['a', 'f']

In [114]:
a = "banana"
2 b = "banana"
>>> a is b

SyntaxError: invalid syntax (<ipython-input-114-c9ad1b94f41f>, line 2)

In [115]:
>>> a = [1, 2, 3]
>>> b = [1, 2, 3]
>>> a == b

True

In [116]:
>>> a is b

False

In [117]:
>>> a = [1, 2, 3]
>>> b = a
>>> a is b

True

In [118]:
>>> b[0] = 5
>>> a

[5, 2, 3]

In [119]:
>>> a = [1, 2, 3]
>>> b = a[:]
>>> b

[1, 2, 3]

In [120]:
>>> b[0] = 5
>>> a

[1, 2, 3]

In [121]:
>>> mylist = []
>>> mylist.append(5)
>>> mylist.append(27)
>>> mylist.append(3)
>>> mylist.append(12)
>>> mylist

[5, 27, 3, 12]

In [122]:
>>> mylist.insert(1, 12) # Insert 12 at pos 1, shift other items up
>>> mylist

[5, 12, 27, 3, 12]

In [123]:
>>> mylist.count(12) # How many times is 12 in mylist?

2

In [124]:
>>> mylist.extend([5, 9, 5, 11]) # Put whole list onto end of mylist
>>> mylist

[5, 12, 27, 3, 12, 5, 9, 5, 11]

In [125]:
>>> mylist.index(9)

6

In [126]:
>>> mylist.reverse()
>>> mylist

[11, 5, 9, 5, 12, 3, 27, 12, 5]

In [127]:
>>> mylist.sort()
>>> mylist

[3, 5, 5, 5, 9, 11, 12, 12, 27]

In [128]:
>>> mylist.remove(12) # Remove the first 12 in the list
>>> mylist

[3, 5, 5, 5, 9, 11, 12, 27]

In [129]:
>>> things = [2, 5, 9]
>>> more_things = double_stuff(things)
>>> things

NameError: name 'double_stuff' is not defined

In [130]:
>>> things = [2, 5, 9]
>>> more_things = double_stuff(things)
>>> more_things

NameError: name 'double_stuff' is not defined

In [131]:
>>> things = [2, 5, 9]
>>> things = double_stuff(things)
>>> things

NameError: name 'double_stuff' is not defined

In [132]:
>>> song = "The rain in Spain..."
>>> words = song.split()
>>> words

['The', 'rain', 'in', 'Spain...']

In [133]:
>>> song = "The rain in Spain..."
>>> song.split("ai")

['The r', 'n in Sp', 'n...']

In [134]:
>>> song = "The rain in Spain..."
>>> glue = ";"
>>> phrase = glue.join(words)
>>> phrase

'The;rain;in;Spain...'

In [135]:
>>> song = "The rain in Spain..."
>>> " --- ".join(words)
'The --- rain --- in --- Spain...'
>>> "".join(words)
'TheraininSpain...'

'TheraininSpain...'

In [136]:
>>> letters = list("Crunchy Frog")
>>> letters

['C', 'r', 'u', 'n', 'c', 'h', 'y', ' ', 'F', 'r', 'o', 'g']

In [137]:
>>> letters = list("Crunchy Frog")
>>> "".join(letters)

'Crunchy Frog'

In [138]:
>>> range(10) # Create a lazy promise
range(0, 10)
>>> list(range(10)) # Call in the promise, to produce a list.

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [139]:
>>> nested = ["hello", 2.0, 5, [10, 20]]

In [140]:
>>> nested = ["hello", 2.0, 5, [10, 20]]
>>> print(nested[3])

[10, 20]


In [141]:
>>> nested = ["hello", 2.0, 5, [10, 20]]
>>> print(nested[3])

[10, 20]


In [142]:
>>> nested = ["hello", 2.0, 5, [10, 20]]
>>> elem = nested[3]
>>> elem[0]

10

In [143]:
>>> mx = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [144]:
>>> mx = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
>>> mx[1]

[4, 5, 6]

In [145]:
>>> mx = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
>>> mx[1][2]

6

In [146]:
>>> list(range(10, 0, -2))

[10, 8, 6, 4, 2]

In [147]:
>>> english_spanish = {}
>>> english_spanish["one"] = "uno"
>>> english_spanish["two"] = "dos"

In [148]:
>>> english_spanish = {}
>>> english_spanish["one"] = "uno"
>>> english_spanish["two"] = "dos"
>>> print(english_spanish)

{'one': 'uno', 'two': 'dos'}


In [149]:
>>> {"apples": 430, "bananas": 312, "oranges": 525, "pears": 217}

{'apples': 430, 'bananas': 312, 'oranges': 525, 'pears': 217}

In [150]:
>>> [('apples', 430), ('bananas', 312), ('oranges', 525), ('pears', 217)]

[('apples', 430), ('bananas', 312), ('oranges', 525), ('pears', 217)]

In [151]:
>>> english_spanish = {"one": "uno", "two": "dos", "three": "tres"}

In [152]:
>>> english_spanish = {"one": "uno", "two": "dos", "three": "tres"}
>>> print(english_spanish["two"])

dos


In [153]:
>>> inventory = {"apples": 430, "bananas": 312, "oranges": 525, "pears": 217}
>>> print(inventory)

{'apples': 430, 'bananas': 312, 'oranges': 525, 'pears': 217}


In [154]:
>>> inventory = {"apples": 430, "bananas": 312, "oranges": 525, "pears": 217}
>>> del inventory["bananas"]
>>> print(inventory)

{'apples': 430, 'oranges': 525, 'pears': 217}


In [ ]:
>>> inventory = {"apples": 430, "bananas": 312, "oranges": 525, "pears": 217}
>>> inventory["bananas"] = 0
>>> print(inventory)

In [155]:
>>> inventory = {"apples": 430, "bananas": 312, "oranges": 525, "pears": 217}
>>> inventory["bananas"] += 200
>>> print(inventory)

{'apples': 430, 'bananas': 512, 'oranges': 525, 'pears': 217}


In [187]:
>>> letter_counts = {}
>>> for letter in "Mississippi":
    letter_counts[letter] = letter_counts.get(letter, 0) + 1
...
>>> letter_counts

{'M': 1, 'i': 4, 's': 4, 'p': 2}

In [185]:
>>> letter_counts = {}
>>> for letter in "Mississippi":
    letter_items = list(letter_counts.items())
>>> letter_items.sort()
>>> print(letter_items)

[]


In [158]:
# This begins the questions for chapter 6
>>> a = [2, 3, 8]
>>> 2 * a

[2, 3, 8, 2, 3, 8]

In [159]:
>>> a = [2, 3, 8]
>>> 2 * a
>>> 2.1 * a

TypeError: can't multiply sequence by non-int of type 'float'

In [161]:
>>> import numpy as np
>>> a = np.array([2, 3, 8])
>>> 2.1 * a

array([ 4.2,  6.3, 16.8])

In [162]:
>>> import numpy as np
>>> a = np.array([2, 3, 8])
>>> a * a

array([ 4,  9, 64])

In [163]:
>>> import numpy as np
>>> a = np.array([2, 3, 8])
>>> a * a
>>> a**2

array([ 4,  9, 64], dtype=int32)

In [164]:
>>> import numpy as np
>>> a = np.array([2, 3, 8])
>>> a.shape

(3,)

In [165]:
>>> import numpy as np
>>> a = np.array([2, 3, 8])
>>> b = np.array([
[2, 3, 8],
[4, 5, 6],
])
>>> b.shape

(2, 3)

In [166]:
>>> a = np.array([2, 3, 8])
>>> a[2]

8

In [167]:
>>> a = np.array([2, 3, 8])
>>> a[1:]

array([3, 8])

In [168]:
>>> b = np.array([
[2, 3, 8],
[4, 5, 6],
])
>>> b[1]

array([4, 5, 6])

In [169]:
>>> b = np.array([
[2, 3, 8],
[4, 5, 6],
])
>>> b[1][2]

6

In [170]:
>>> b = np.array([
[2, 3, 8],
[4, 5, 6],
])
>>> b[:, 1]

array([3, 5])

In [171]:
>>> a = np.array([230, 10, 284, 39, 76])
>>> cutoff = 200
>>> a > cutoff

array([ True, False,  True, False, False])

In [172]:
>>> a = np.array([230, 10, 284, 39, 76])
>>> cutoff = 200
>>> a[a > cutoff] = 0
>>> a

array([ 0, 10,  0, 39, 76])

In [173]:
>>> a = np.array([230, 10, 284, 39, 76])
>>> cutoff = 200
>>> new_a = []
>>> for x in a:
>>> if x > cutoff:
>>> new_a.append(0)
>>> else:
>>> new_a.append(x)
>>> a = np.array(new_a)

IndentationError: expected an indented block (<ipython-input-173-587f63e1b060>, line 5)

In [174]:
>>> a = np.array([
[0, 1],
[2, 3],
[4, 5],
])
>>> b = np.array([10, 100])
>>> a * b

array([[  0, 100],
       [ 20, 300],
       [ 40, 500]])

In [175]:
>>> a = np.array([
[0, 1],
[2, 3],
[4, 5],
])
>>> c = np.array([
[0, 1, 2],
[3, 4, 5],
])
>>> b = np.array([10, 100])
>>> c * b

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [176]:
>>> a = np.array([
[0, 1],
[2, 3],
[4, 5],
])
>>> c = np.array([
[0, 1, 2],
[3, 4, 5],
])
>>> b = np.array([10, 100])
>>> c * b[:, None]

array([[  0,  10,  20],
       [300, 400, 500]])

In [177]:
>>> import numpy as np
>>> a = np.array([200], dtype='uint8')
>>> a + a

array([144], dtype=uint8)

In [178]:
>>> import numpy as np
>>> a = np.array([200], dtype='uint16')
>>> a + a

array([400], dtype=uint16)

In [179]:
>>> import numpy as np
>>> a = np.array([200], dtype='uint8')
>>> a.astype('uint64')

array([200], dtype=uint64)

In [180]:
>>> wordsfile = open("/usr/share/dict/words", "r")
>>> wordlist = wordsfile.readlines()
>>> print(wordlist[:6])
['\n', 'A\n', "A's\n", 'AOL\n', "AOL's\n", 'Aachen\n']

FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/dict/words'